collections:
  authors:
    output: true
baseurl: "/blog"
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "blog"
    values:
      layout: "default"

title: "My Blog"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
